name: "build-docker"

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
      - "master"
    paths:
      - "./**"
  pull_request:
    branches:
      - "main"
      - "master"
    paths:
      - "Dockerfile*"

jobs:
  docker_buildx_debian:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract Version
        run: |
          export MONERO_VERSION="$(git describe)"
          echo "MONERO_VERSION=$MONERO_VERSION" >> $GITHUB_ENV

      - name: Build and push latest Debian image
        uses: docker/build-push-action@v6.5.0
        with:
          context: ./
          file: ./Dockerfile
          platforms: |
            linux/amd64
            linux/386
            linux/arm64
            linux/arm/v7
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            thormme/devpi-client:latest
            thormme/devpi-client:${{ env.MONERO_VERSION }}